import React, {useEffect,useState} from 'react';
import {ActivityIndicator,Text,TextInput,View} from 'react-native';
import {request} from './api';
import {Action} from './Account';
import {s,colors} from './styles';
export default function Records(){
  const [mode,setMode]=useState('Rankings'),[format,setFormat]=useState('T20'),[category,setCategory]=useState('team'),[gender,setGender]=useState('men'),[search,setSearch]=useState(''),[profileId,setProfileId]=useState(null),[data,setData]=useState(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
  useEffect(()=>{const controller=new AbortController();setData(null);setError('');const path=profileId?'/history/'+encodeURIComponent(profileId):mode==='Rankings'?`/rankings?format=${format}&category=${category}&gender=${gender}`:mode==='Records'?`/records?format=${format}`:'/history?search='+encodeURIComponent(search);const timer=setTimeout(()=>request(path,controller.signal).then(v=>{if(!controller.signal.aborted)setData(v);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}),search?250:0);return()=>{clearTimeout(timer);controller.abort();};},[mode,format,category,gender,search,profileId,retry]);
  const choices=(values,current,change)=><View style={s.filters}>{values.map(v=><Action key={v} title={v} secondary={v!==current} onPress={()=>{if(v!==current){setData(null);change(v);}}} />)}</View>;
  return <View><Text style={s.kicker}>THE CRICKET ARCHIVE</Text><Text style={s.pageTitle}>Records & legacy</Text>
    {profileId?<Action title="Back to archive" secondary onPress={()=>{setData(null);setProfileId(null);}} />:<>{choices(['Rankings','Records','History'],mode,setMode)}{mode!=='History'&&choices(['T20','ODI','TEST'],format,setFormat)}{mode==='Rankings'&&<>{choices(['team','batting','bowling','allrounder'],category,setCategory)}{choices(['men','women'],gender,setGender)}</>}{mode==='History'&&<TextInput accessibilityLabel="Search players or teams" placeholder="Search players or teams" value={search} onChangeText={setSearch} maxLength={80} style={{padding:14,borderWidth:1,borderColor:colors.line,borderRadius:8,marginVertical:16}} />}</>}
    {!!error&&<View style={s.card}><Text accessibilityRole="alert" style={s.body}>{error}</Text><Action title="Try again" onPress={()=>setRetry(n=>n+1)} /></View>}
    {!data&&!error&&<ActivityIndicator color={colors.green} style={s.loader} />}
    {data&&(profileId?<View style={s.card}><Text style={s.heading}>{data.name}</Text><Text style={s.category}>{data.team} · {data.kind}</Text><Text style={s.meta}>{data.career_start} – {data.career_end||'present'} · {data.source_label}</Text><Text style={s.paragraph}>{data.biography}</Text><Text style={s.heading}>Career statistics</Text>{data.statistics.map((v,i)=><View style={s.infoRow} key={i}><Text style={s.body}>{v.format} · {v.label}</Text><Text style={s.infoValue}>{v.value}</Text></View>)}<Text style={[s.heading,{marginTop:20}]}>Achievements</Text>{data.achievements.map((a,i)=><View style={s.infoRow} key={i}><Text style={s.category}>{a.year}</Text><View style={{flex:1,marginLeft:14}}><Text style={s.player}>{a.title}</Text><Text style={s.body}>{a.description}</Text></View></View>)}<Text style={[s.heading,{marginTop:20}]}>Records</Text>{data.records.map((r,i)=><Text key={i} style={s.body}>{r.format} · {r.title}: {r.value}</Text>)}</View>:mode==='Rankings'?<View style={s.card}><Text style={s.heading}>{format} rankings</Text><Text style={s.meta}>{data.source_label||'No rankings available'}{data.as_of?' · '+new Date(data.as_of).toLocaleDateString():''}</Text>{data.entries.map(r=><View key={r.rank} style={s.infoRow}><Text style={s.score}>{r.rank}</Text><View style={{flex:1,marginLeft:14}}><Text style={s.player}>{r.name}</Text><Text style={s.meta}>{r.team} · {r.rating} points · {r.previous_rank==null?'New':r.previous_rank===r.rank?'Unchanged':r.previous_rank>r.rank?'↑ '+(r.previous_rank-r.rank):'↓ '+(r.rank-r.previous_rank)}</Text>{r.profile_id&&<Action title="Career & achievements" secondary onPress={()=>{setData(null);setProfileId(r.profile_id);}} />}</View></View>)}</View>:<>{!data.length&&<Text style={s.body}>No results found.</Text>}{data.map(r=><View style={s.card} key={r.id}><Text style={s.heading}>{r.title||r.name}</Text>{mode==='Records'?<><Text style={s.score}>{r.value}</Text><Text style={s.player}>{r.holder_name} · {r.format}</Text><Text style={s.body}>{r.context}</Text>{r.achieved_on&&<Text style={s.meta}>{new Date(r.achieved_on).toLocaleDateString()}</Text>}</>:<Text style={s.body}>{r.team} · {r.career_start} – {r.career_end||'present'}</Text>}<Text style={s.meta}>{r.source_label}</Text>{(mode==='History'||r.profile_id)&&<Action title="View history & achievements" secondary onPress={()=>{setData(null);setProfileId(r.profile_id||r.id);}} />}</View>)}</>)}
  </View>;
}
