import { StyleSheet } from 'react-native';
export const colors = { green: '#087f5b', ink: '#152a25', muted: '#65766f', line: '#e0e8e3', paper: '#f3f6f3', lime: '#d9f88c' };
export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.paper }, white: { color: '#fff' }, light: { color: '#c1d8c8' },
  header: { backgroundColor: '#fff', paddingHorizontal: 22, paddingVertical: 18, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: colors.line },
  brand: { fontSize: 27, fontWeight: '900', color: colors.ink, letterSpacing: -1 },
  meta: { fontSize: 12, color: colors.muted, lineHeight: 18 }, demoBadge: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 6, backgroundColor: '#e7efe9' }, demoText: { fontSize: 12, fontWeight: '800', color: colors.green, letterSpacing: 1 },
  content: { padding: 18, paddingBottom: 30, width: '100%', maxWidth: 720, alignSelf: 'center' },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginVertical: 8 }, kicker: { fontSize: 12, fontWeight: '700', color: colors.green, letterSpacing: 2 }, pageTitle: { fontSize: 34, color: colors.ink, fontWeight: '800', marginTop: 7, letterSpacing: -1 },
  liveCount: { fontSize: 12, fontWeight: '800', color: colors.green }, notice: { paddingVertical: 12 }, noticeText: { color: colors.muted, fontSize: 12, lineHeight: 18 },
  filters: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 18, marginTop: 6 }, button: { minHeight: 44, paddingHorizontal: 14, paddingVertical: 11, borderRadius: 8, backgroundColor: '#e7ede8', justifyContent: 'center', alignItems: 'center' }, buttonActive: { backgroundColor: colors.green }, buttonText: { fontSize: 14, color: colors.ink, fontWeight: '600' },
  card: { padding: 20, backgroundColor: '#fff', borderRadius: 16, borderWidth: 1, borderColor: colors.line, marginBottom: 14 }, featured: { backgroundColor: '#164c38', borderColor: '#164c38' },
  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8, flexWrap: 'wrap' }, eyebrow: { fontSize: 12, fontWeight: '700', color: colors.muted, letterSpacing: 1 }, status: { fontSize: 12, fontWeight: '800', color: colors.muted }, series: { fontSize: 14, color: colors.muted, marginTop: 7, marginBottom: 16 },
  teamRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 14, gap: 10 }, teamBadge: { width: 44, height: 38, borderRadius: 8, backgroundColor: '#e9f1ea', alignItems: 'center', justifyContent: 'center' }, teamCode: { fontSize: 12, fontWeight: '800', color: colors.green }, teamName: { flex: 1, fontSize: 16, fontWeight: '600', color: colors.ink }, scoreBlock: { alignItems: 'flex-end' }, score: { fontSize: 24, fontWeight: '800', color: colors.ink, fontVariant: ['tabular-nums'] }, matchSummary: { color: colors.green, fontSize: 14, lineHeight: 21, paddingTop: 14, borderTopWidth: 1, borderTopColor: colors.line },
  heading: { fontSize: 18, fontWeight: '700', color: colors.ink }, body: { fontSize: 16, lineHeight: 25, color: colors.muted }, empty: { padding: 30, alignItems: 'center' }, error: { padding: 18, backgroundColor: '#fff0dc', borderRadius: 12, marginBottom: 16 }, loader: { padding: 60 },
  newsCard: { backgroundColor: '#fff', padding: 22, borderRadius: 14, marginBottom: 16, borderWidth: 1, borderColor: colors.line, borderTopWidth: 4, borderTopColor: colors.green }, category: { fontSize: 12, fontWeight: '800', color: colors.green, letterSpacing: 0.8 }, articleTitle: { fontSize: 23, lineHeight: 30, fontWeight: '800', color: colors.ink, marginVertical: 14 }, readerTitle: { fontSize: 30, lineHeight: 38, fontWeight: '800', color: colors.ink, marginVertical: 18 }, paragraph: { fontSize: 17, lineHeight: 28, color: colors.ink, marginTop: 22 },
  back: { alignSelf: 'flex-start', marginBottom: 16 }, infoRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 18, marginTop: 20 }, infoValue: { color: colors.ink, fontSize: 16, textAlign: 'right', flex: 1, lineHeight: 24 },
  tableRow: { flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: colors.line, paddingVertical: 14 }, tableName: { flex: 1, paddingRight: 5 }, cell: { width: 30, fontSize: 14, color: colors.ink, textAlign: 'right' }, player: { fontSize: 14, color: colors.ink, fontWeight: '600', lineHeight: 21 },
  commentRow: { flexDirection: 'row', gap: 18, paddingVertical: 20, borderBottomWidth: 1, borderBottomColor: colors.line }, runBadge: { marginTop: 8, width: 32, height: 32, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.paper, borderRadius: 16 },
  footer: { color: colors.muted, fontSize: 12, textAlign: 'center', letterSpacing: 2, paddingTop: 20 }, navigation: { backgroundColor: '#fff', flexDirection: 'row', borderTopWidth: 1, borderTopColor: colors.line, paddingVertical: 9 }, navItem: { flex: 1, alignItems: 'center', paddingVertical: 5, minHeight: 52 }, navIcon: { fontSize: 23, color: colors.muted }, navLabel: { fontSize: 12, color: colors.muted, marginTop: 3 }
});
